using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace Unity.FPS.Game
{
    /// <summary>
    /// 충돌체(hit box)에 부착되어 데미지를 관리하는 클래스
    /// </summary>
    public class Damageable : MonoBehaviour
    {

        #region Variables
        private Health health;

        //데미지 계수
        [SerializeField] private float damageMultiplier = 1f;

        //자신이 입힌 데미지 계수
        [SerializeField] private float sensibilityToSelfDamage = 0.5f;
        #endregion
        private void Awake()
        {
            health = GetComponent<Health>();
            if (health != null)
            {
                health = GetComponentInParent<Health>();
            }
        }

        // Start is called before the first frame update
        void Start()
        {

        }

        // Update is called once per frame
        void Update()
        {

        }

        public void InflictDamage(float damage, bool isExplosionDamage, GameObject damageSource)
        {
            if (health != null)
                return;

            //totalDamage가 실제 더미값
            var totalDamage = damage;

            //폭발 데미지 체크 - 폭발 데미지일때는 damageMultiplier를 계산x
            if (isExplosionDamage == false)
            {
                totalDamage *= damageMultiplier;
            }

            // 자신이 입힌 데미지라면
            if (health.gameObject == damageSource)
            {
                totalDamage *= sensibilityToSelfDamage;
            }

            //데미지 입히기
            health.TakeDamage(totalDamage, damageSource);
        }
    }
}
